### ISSUE TITLE
Cmake build error on Windows,ftgl not found

### ISSUE THREAD

**Issue by LaiZhou** [captnfab/PianoBooster#281]
GUI system is WIN32 MinGW Makefiles
PREFIX: C:/Program Files (x86)/pianobooster
DATA_DIR: share/games/pianobooster
CMAKE_INSTALL_BINDIR: bin
-- Found OpenGL: opengl32
CMake Error at src/CMakeLists.txt:64 (FIND_PACKAGE):
  By not providing "Findftgl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ftgl", but
  CMake did not find one.

But the ftgl was already installed by pacman. The cmake path prefix is D:\msys64\mingw64\bin.

cmake.exe -G "MinGW Makefiles" ..

@louis-barman @glixx  @admsasha 
Would someone help me ?

**Comment by louis-barman** [comment]
Sorry I should have got back to you earlier you need these two files and then edit them to match your system.
[cmake-files.zip](https://github.com/pianobooster/PianoBooster/files/5861147/cmake-files.zip)

and then set these two environmental variables to point to your .cmake files.

```
set ftgl_DIR=C:\Home\lb\prj\pb\config\
set fluidsynth_DIR=C:\Home\lb\prj\pb\config\
```

I hope that helps. or did you already get it working?

**Comment by LaiZhou** [comment]
@louis-barman , I use msys2 to manage the packages.
 I need modfify the CmakeLists.txt,use pkg-config to find the library dir path:
if USE_FTGL and WIN32 ,then：
`  pkg_check_modules(FTGL ftgl)  
      if(NOT FTGL_FOUND)
         MESSAGE(FATAL_ERROR "FTGL was not found")
      endif(NOT FTGL_FOUND)
      SET(FTGL_INCLUDE_DIR ${FTGL_INCLUDE_DIRS})
      SET(FTGL_LIBRARY ${FTGL_LIBRARIES})   
`
