### ISSUE TITLE
midi files with more than two channels

### ISSUE THREAD

**Issue by aromanro** [captnfab/PianoBooster#288]
I have a midi file that has three channels. Two of them would be for the left hand.

Unfortunately, I can select only one of them for the left hand.

Would it be possible to allow selecting more than one channel for a hand?

Thank you!

**Comment by louis-barman** [comment]
Sorry, there are no plans to do this especially as it would be very difficult to implement. I recommend you use a program like MuseScore to merge both left hand parts into a single midi channel which is the quickest solution.

**Comment by aromanro** [comment]
I had to try :)
