### ISSUE TITLE
Question regarding notes duration checks and symbols

### ISSUE THREAD

**Issue by andre2007** [captnfab/PianoBooster#291]
If my understanding is correct, independent of the note duration(whole, half, quarter...) always the same symbol is shown (a filled circle). 
![image](https://user-images.githubusercontent.com/1451047/110990208-4fe7c880-8373-11eb-8f17-b1052d2caaf8.png)

This looks confusing for me. Is it possible to show instead the common note symbols like
![image](https://user-images.githubusercontent.com/1451047/110990699-f16f1a00-8373-11eb-9a45-446f23f652eb.png)

Also in this direction, it seems the program only checks whether I play the right note at the right time (timing markers) but not if I play the note long enough. This feature would be quite interesting to practice rhythmus.

A third question. Could you add an option to hide these brown vertical lines on each note? It is quite hard to concentrate on the notes as these brown vertical lines deviates.

**Comment by louis-barman** [comment]
Please can you repost this Question to the user forum http://piano-booster.2625608.n2.nabble.com/Piano-Booster-Users-f1591936.html and I'll reply over there thanks.

**Comment by andre2007** [comment]
@louis-barman I reposted the question here http://piano-booster.2625608.n2.nabble.com/Questions-regarding-notes-duration-checks-and-symbols-td7572958.html

**Comment by louis-barman** [comment]
I have just posted my detailed reply on the forum. So closing this issue. Thanks.
